language: go
sudo: false

os:
  - linux

go:
  - "1.12"
  - "1.13"

env:
  - GO111MODULE=on

before_install:
  - go mod vendor
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci -race -show -package github.com/renard/go-cwformatter
